[package]
name = "mina-token-mobile"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-ff = "0.5"
flate2 = "1"
jni = "0.22.4"
ledger = { package = "mina-tree", git = "https://github.com/youtpout/mina-rust", branch = "pickle-rs" }
mina-curves = { git = "https://github.com/youtpout/proof-systems", branch = "pickle-rs" }
mina-p2p-messages = { git = "https://github.com/youtpout/mina-rust", branch = "pickle-rs" }
mina-runtime = { git = "https://github.com/youtpout/mina-rust", branch = "pickle-rs" }
mina-signer = { git = "https://github.com/youtpout/proof-systems", branch = "pickle-rs" }
pickles = { git = "https://github.com/youtpout/proof-systems", branch = "pickle-rs" }
poseidon = { git = "https://github.com/youtpout/mina-rust", branch = "pickle-rs" }
reqwest = { version = "0.12.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = true

[patch.crates-io]
num-bigint = { git = "https://github.com/openmina/num-bigint", branch = "rebase-onstack" }
