#!/usr/bin/env bash
#
# Writes ios/Sources/Defaults.generated.swift, the form's build-time defaults,
# from the repository-root .env.local — the same file and the same keys the
# Gradle build reads. The values land inside the binary, so only throwaway
# Devnet keys belong there.
#
# Called by build-macos.sh and by the Xcode project's pre-build phase.
#
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
env_local="$(cd "$here/.." && pwd)/.env.local"

env_default() {
  local key=$1 fallback=${2-}
  local value=""
  if [ -f "$env_local" ]; then
    value=$(sed -n "s/^${key}=//p" "$env_local" | tail -n 1)
  fi
  printf '%s' "${value:-$fallback}"
}

swift_string() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

{
  echo "// Generated by ios/generate-defaults.sh from .env.local — do not edit."
  echo "enum Defaults {"
  echo "    static let senderPrivateKey = \"$(swift_string "$(env_default MINA_PRIVATE_KEY)")\""
  echo "    static let receiver = \"$(swift_string "$(env_default MINA_RECEIVER_ADDRESS)")\""
  echo "    static let amount = \"$(swift_string "$(env_default MINA_TRANSFER_AMOUNT 1000000000)")\""
  echo "    static let tokenAddress = \"$(swift_string "$(env_default MINA_TOKEN_ADDRESS)")\""
  echo "    static let graphqlUrl = \"$(swift_string \
    "$(env_default MINA_GRAPHQL_URL https://mina-devnet-graphql.aurowallet.com/graphql)")\""
  echo "}"
} > "$here/Sources/Defaults.generated.swift"
